config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  get "/roadmap" => "topics#index"
  get "/introduce-yourself" => "pages#introduction", as: "introduce_yourself"

  get "/emails" => "users#emails", as: "emails"

  post "/newsletter-signup" => "users#newsletter_signup", as: "newsletter_signup"

  resources :charges
  resources :responses, except: [:index, :show]
  resources :topics
end

app/models/password_generator.rb
class PasswordGenerator
  def self.generate
    (0...8).map { ('a'..'z').to_a[rand(26)] }.join
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :email, :body, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId

  friendly_id :name, use: :slugged

  default_scope { order('id') }
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  protect_from_forgery with: :null_session

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'rubyonrichards' && password == 'thisisnotcool'
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 7000

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    redirect_to root_path, notice: "Thanks! You'll receive an email with our materials shortly."

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @user = User.new
  end

  def introduction
    @response = Response.new
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

  before_action :set_response, only: [:show, :edit, :update, :destroy]

  def index
    @responses = Response.all
  end

  def show
  end

  def new
    @response = Response.new
  end

  def edit
  end

  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        ResponseMailer.response_email(params[:response][:full_name], params[:response][:body]).deliver_now

        user = User.new(email: params[:response][:email], password: PasswordGenerator.generate, full_name: params[:response][:full_name]).save

        format.html { redirect_to root_path, notice: "Thank you for getting in touch! We will get back to you within 24 hours." }
      else
        format.html { render :new }
      end
    end

  end

  def update
    respond_to do |format|
      if @response.update(response_params)
        format.html { redirect_to @response, notice: 'Response was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @response.destroy
    respond_to do |format|
      format.html { redirect_to responses_url, notice: 'Response was successfully destroyed.' }
    end
  end

  private

  def set_response
    @response = Response.find(params[:id])
  end

  def response_params
    params.require(:response).permit(:full_name, :email, :body, :referral_code)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = Topic.all
  end

  def new
    @topic = Topic.new
  end

  def show
  end

  def edit
  end

  def update
    @topic.update_attributes(topic_params)

    redirect_to @topic
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.save!

    redirect_to topics_path
  end

  def destroy
    @topic.destroy

    redirect_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:name, :content)
  end

  def set_topic
    @topic = Topic.friendly.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  skip_before_filter  :verify_authenticity_token

  before_filter :authenticate, only: :emails

  def newsletter_signup
    user = User.new(email: params[:email], password: PasswordGenerator.generate).save
    flash[:notice] = "Thanks for signing up!"
    redirect_to root_path
  end

  def emails
    @emails = User.all.map(&:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
    <p><%= flash[:error] %></p>
  </div>
<% end %>
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_head.html.erb
<meta charset="utf-8" />
<title>Your Code Mentor | Ruby on Richards</title>
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="author" content="">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
<meta name="google-site-verification" content="uierz2rfSVeVS9f9AJczi45BymbO6CT-fGYq6YmK0UA" />

<!-- Favicone Icon -->
<%= favicon_link_tag 'favicon.ico' %>
<%# <link rel="icon" type="image/png" href="img/favicon.png" /> %>
<%# <link rel="apple-touch-icon" href="img/favicon.png" /> %>

<!-- Css -->
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" />
<link href="css/plugins/animate.css" rel="stylesheet" type="text/css" />
<!-- SLIDER REVOLUTION CSS SETTINGS -->
<link rel="stylesheet" type="text/css" href="rs-plugin/css/settings.css" media="screen" />

app/views/layouts/_js.html.erb
<!-- Js -->
<script src="js/jquery-1.11.2.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.easing.1.3.js" type="text/javascript"></script>
<script src="js/plugins/bootstrap.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.fitvids.js" type="text/javascript"></script>
<script src="js/plugins/jquery.stellar.min.js" type="text/javascript"></script>
<script src="js/plugins/isotope.pkgd.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.appear.js" type="text/javascript"></script>
<script src="js/plugins/jquery.fs.tipper.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.countTo.js" type="text/javascript"></script>
<script src="js/plugins/owl.carousel.min.js" type="text/javascript"></script>
<!-- SLIDER REVOLUTION SCRIPTS  -->
<script src="rs-plugin/js/jquery.themepunch.tools.min.js" type="text/javascript"></script>
<script src="rs-plugin/js/jquery.themepunch.revolution.min.js" type="text/javascript"></script>
<!-- End SLIDER REVOLUTION SCRIPTS  -->
<script src="js/plugins/jquery.magnific-popup.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.singlePageNav.min.js" type="text/javascript"></script>
<script src="js/plugins/wow.min.js" type="text/javascript"></script>
<script src="js/plugins/jquery.validate.min.js" type="text/javascript"></script>
<script src="js/contact-form.js" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script src="js/map.js" type="text/javascript"></script>
<script src="js/theme.js" type="text/javascript"></script>

<script type="text/javascript">(function(d,n){var s,a,p;s=document.createElement("script");s.type="text/javascript";s.async=true;s.src=(document.location.protocol==="https:"?"https:":"http:")+"//cdn.nudgespot.com"+"/nudgespot.js";a=document.getElementsByTagName("script");p=a[a.length-1];p.parentNode.insertBefore(s,p.nextSibling);window.nudgespot=n;n.init=function(t){function f(n,m){var a=m.split('.');2==a.length&&(n=n[a[0]],m=a[1]);n[m]=function(){n.push([m].concat(Array.prototype.slice.call(arguments,0)))}}n._version=0.1;n._globals=[t];n.people=n.people||[];n.params=n.params||[];m="track register unregister identify set_config people.delete people.create people.update people.create_property people.tag people.remove_Tag".split(" ");for(var i=0;i<m.length;i++)f(n,m[i])}})(document,window.nudgespot||[]);nudgespot.init("1a74053906ede717c0abb0c5fbfeeab3");</script>

<!--  Google Analytice -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)
},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-80910236-1', 'auto');
ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%# <a class="navbar-brand" href="#">Project name</a> %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%# <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> %>
          <ul class="dropdown-menu">
            <li><a href="/blog">Blog</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/blog">BLOG</a></li>
        <li><a href="/introduce-yourself">SAY HELLO</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav> <!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <%= image_tag("/img/logo-gold-no-border.png")%>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <%# <li class="active"><a href="#">Home</a></li> %>
        <%# <li><a href="#about">About</a></li> %>
        <%# <li><a href="#contact">Contact</a></li> %>
        <%# <li class="dropdown"> %>
        <%#   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a> %>
        <%#   <ul class="dropdown-menu"> %>
        <%#     <li><a href="#">Action</a></li> %>
        <%#     <li><a href="#">Another action</a></li> %>
        <%#     <li><a href="#">Something else here</a></li> %>
        <%#     <li role="separator" class="divider"></li> %>
        <%#     <li class="dropdown-header">Nav header</li> %>
        <%#     <li><a href="#">Separated link</a></li> %>
        <%#     <li><a href="#">One more separated link</a></li> %>
        <%#   </ul> %>
        <%# </li> %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/blog">BLOG</a></li>
        <li><a class="say-hello animated infinite pulse" href="/introduce-yourself">SAY HELLO</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/_stripe_button.html.erb
<%= form_tag charges_path, id: 'chargeForm' do %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <%= hidden_field_tag 'stripeToken' %>
  <%= hidden_field_tag 'stripeEmail' %>
  <button id="customButton" class="btn btn-md btn-black">Buy Now</button>

  <script>
    var handler = StripeCheckout.configure({
      key: '<%= ENV["STRIPE_PUBLISHABLE"] %>',
      image: 'img/logo.svg',
      token: function(token, args) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
    });

    document.getElementById('customButton').addEventListener('click', function(e) {
      // Open Checkout with further options
      handler.open({
        name: 'Ruby on Richards',
        description: 'Interested Plan ($70.00)',
        amount: 70*100,
      });
      e.preventDefault();
    });
  </script>
<% end %>

app/views/layouts/_testimonials.html.erb
<!-- Testimonials Section-->
<section id="testimonials" class="section-padding overlay-dark dark-bg bg-image text-center" data-stellar-background-ratio="0.5" data-background-img="img/full/code.jpg">
  <div class="container">
    <div class="owl-carousel testimonial-carousel nf-carousel-theme white">

      <div class="item">
        <div class="testimonial text-center max-width-700">
          <div class="page-icon-sm"><i class="fa fa-quote-right"></i></div>
          <p class="lead">Dylan is a great developer with an eye for best practices and design patterns. His passion for programming is only matched by his desire to help others learn.</p>
          <h6 class="quote-author">Ryan Couto  <span style="font-weight: 400;">(Twitter)<span></h6>
        </div>
      </div>

      <div class="item">
        <div class="testimonial text-center max-width-700">
          <div class="page-icon-sm"><i class="fa fa-quote-right"></i></div>
          <p class="lead">I had a talk accepted at Ruby Remote Conf this summer! Thanks for inspiring me, Dylan.</p>
          <h6 class="quote-author">Esther L. <span style="font-weight: 400;">(Bootcamp Graduate)<span></h6>
        </div>
      </div>

    </div>
  </div>
</section>
<!-- End Testimonials Section -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby On Richards</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <%= render "layouts/head" %>
  </head>

  <body>

    <%= render "layouts/navbar" %>

    <%= yield %>

    <%= render "pages/footer" %>

    <%= render "layouts/js" %>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>

<html>
  <head>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_about.html.erb
<!-- About Section -->
<section id="about" class="section-padding text-center">
  <div class="container mb-60">
    <h2><span class="text-light">Never thought </span>you could program?</h2>
    <p class="max-width-700 lead">
    Let's change that. Our easy to digest curriculum, along with
    clear, friendly, and practical mentorship will
    help you to connect the conceptual dots that most
    struggle with for months.
    </p>
  </div>

  <div class="container">

    <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-heart"></i></div>
        <h5 class="features-title">1-on-1 Mentorship</h5>

        <p>
        Though it's possible to learn software development fundamentals on your
        own, having an experienced mentor can cut your learning time in half.
        Our instructors are available around the clock to answer your questions
        <i>as they arise</i>.
        </p>

      </div>

      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.4s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-magnifier"></i></div>
        <h5 class="features-title">Personal Code Reviews</h5>

        <p>
        Honest and constructive feedback is essential to a software developer's growth. All of the code you write
        will receive a review by our instructors.
        </p>

      </div>

      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.4s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-hammer"></i></div>
        <h5 class="features-title">Watch a professional build real applications</h5>

        <p>
        Have you ever wondered how Facebook, Twitter, and Reddit work? Look no further.
        You will have the opportunity to code along with our instructors as they build real-world, enterprise
        web apps.
        </p>

      </div>

    </div>

    <div class="row">

      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-webpage-img-txt"></i></div>
        <h5 class="features-title">A Portfolio of Web Applications</h5>

        <p>
        Our curriculum is project-based. Not only is working on projects the best way to
        practice the skills you learn, it is also a great way to demonstrate your technical prowess
        to employers.
        </p>

      </div>

      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.6s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-archive-full"></i></div>
        <h5 class="features-title">The most credible learning resources, handpicked</h5>

        <p>
        There's <i>a lot</i> of information out there -- and not all of it is
        worth reading or watching. Leave it to us to filter through the misinformation
        and provide you with the best instructional content there is.
        </p>

      </div>

      <div class="col-md-4 col-sm-6 col-xs-12 content-box mb-sm-30 wow fadeIn" data-wow-delay="0.6s" data-wow-duration="2s">
        <div class="icon-top"><i class="icon icon-basic-lightbulb"></i></div>
        <h5 class="features-title">Interview and Job Search Preparation</h5>

        <p>
        From effective resume and cover letter writing to salary negotiation, we will guide you until you are hired.
        </p>

      </div>

    </div>
  </div>
</section>
<!-- End About Section -->

app/views/pages/_contact_form.html.erb
<!-- Contact Form -->
    <section id="contact-us" class="section-padding dark-bg bg-image overlay-dark60" data-background-img="img/full/20.jpg" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row text-center">
          <h6 class="page-title-alt color mb-15">Wanna say hello? </h6>
          <h2 class="page-title">Get In <span class="text-light">Touch</span></h2>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <div class="row">
              <form id="contact" class="contact-form" role="form">
                <div class="col-md-12 text-center">
                  <h5 class="successContent">
                    <i class="fa fa-check left" style="color: #5cb45d;"></i>Your message has been sent successfully.
                  </h5>
                  <h5 class="errorContent" style="color: #e1534f;">
                    <i class="fa fa-exclamation-circle left"></i>There was a problem validating the form please check!
                  </h5>
                </div>
                <div class="col-md-6">
                  <div class="form-field-wrapper">
                    <input class="input-md form-full" id="form-name" type="text" name="form-name" placeholder="Your Name" required />
                  </div>
                  <div class="form-field-wrapper">
                    <input class="input-md form-full" id="form-email" type="email" name="form-email" placeholder="Email" required />
                  </div>
                  <div class="form-field-wrapper">
                    <input class="input-md form-full" id="form-subject" type="text" name="form-subject" placeholder="Subject" />
                  </div>
                </div>
                <div class="col-md-6 mb-0">
                  <div class="form-field-wrapper">
                    <textarea class="input-md form-full" id="form-message" rows="7" name="form-message" placeholder="Your Message" required></textarea>
                  </div>
                </div>
                <div class="col-md-12 text-center">
                  <button class="btn-contact-submit btn btn-md btn-color" type="submit" id="form-submit" name="submit">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- End Contact Form -->

app/views/pages/_contact_info.html.erb
<!--Contact Info Section-->
<section id="contact-info" class="section-padding">
  <div class="container text-center">
    <div class="row">
      <!-- <div class="col-md-4 mb-sm-30 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s">
        <div class="alt-icon-sm-top"><i class="icon icon-basic-geolocalize-05"></i></div>
        <h5 class="features-title">Address</h5>
        <p>
        801 Dexter Avenue North<br />
        Seattle, WA 98109
        </p>
        </div> -->
        <div class="col-md-6 mb-sm-30 wow fadeIn" data-wow-delay="0.4s" data-wow-duration="2s">
          <div class="alt-icon-sm-top"><i class="icon icon-basic-alarm"></i></div>
          <h5 class="features-title">Active Time Zone</h5>
          <p>9AM - 9PM Pacific<br /></p>
        </div>
        <div class="col-md-6 mb-sm-30 wow fadeIn" data-wow-delay="0.6s" data-wow-duration="2s">
          <div class="alt-icon-sm-top"><i class="icon icon-basic-headset"></i></div>
          <h5 class="features-title">Contact</h5>
          <p class="contact-link">
          <a href="mailto:team@rubyonrichards.com"><span class="text-bold">Email :</span> team@rubyonrichards.com</a><br />
          <a><span class="text-bold">Call :</span> 516-967-2755</a>
          </p>
        </div>
    </div>
  </div>
</section>
<!-- End Contact Info Section-->

app/views/pages/_day_to_day.html.erb
<!-- Work Process Section -->
    <section id="process" class="section-padding">
      <div class="container text-center">
        <h2 class="page-title">Your <span class="text-light">Day-to-day</span></h2>
      </div>
  <div class="container mb-60">
    <p class="max-width-700 lead" style="text-align: center;">
    We've designed our program to be difficult enough to make you think, but not
    so difficult that you become discouraged.
    </p>
  </div>
      <div class="container text-center">
        <div class="row">

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.2s" data-wow-duration="2s" data-toggle="tooltip" 
          title= "Watch a profressional developer solve and explain problems in 1-hour-long lectures, three times per week.">
            <div class="process-icon alt-icon-top"><i class="icon icon-basic-headset"></i></div>
            <h6>Attend lectures</h6>
          </div>

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.4s" data-wow-duration="2s" data-toggle="tooltip"
          title="Assignments are based on your skill level and help to bolster your portfolio.">
            <div class="process-icon alt-icon-top"><i class="icon icon-basic-todolist-pencil"></i></div>
            <h6>Do assignments</h6>
          </div>

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.6s" data-wow-duration="2s" data-toggle="tooltip" 
          title="Learn from the industry's best developers.">
            <div class="process-icon alt-icon-top"><i class="icon icon-basic-book"></i></div>
            <h6>Read books</h6>
          </div>

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="0.8s" data-wow-duration="2s" data-toggle="tooltip" 
          title="Solve fun and challenging problems with another programmer.">
            <div class="process-icon alt-icon-top"><i class="fa fa-users"></i></div>
            <h6>Pair program</h6>
          </div>

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="1s" data-wow-duration="2s" data-toggle="tooltip" 
          title="Weekly check-ins will keep you on track and focus on your areas for improvement.">
            <div class="process-icon alt-icon-top"><i class="fa fa-check"></i></div>
            <h6>Check-in</h6>
          </div>

          <div class="process-box col-md-2 col-sm-4 col-xs-6 wow fadeIn" data-wow-delay="1.2s" data-wow-duration="2s" data-toggle="tooltip" 
          title="We will conduct mock-interviews and help you prepare for code challenges when you're ready.">
            <div class="process-icon alt-icon-top"><i class="fa fa-graduation-cap"></i></div>
            <h6>Interview for jobs</h6>
          </div>

        </div>
      </div>
    </section>
    <!-- End Work Process Section -->

app/views/pages/_remodal.html.erb
<div class="remodal" data-remodal-id="modal">
  <button data-remodal-action="close" class="remodal-close"></button>
  <div id="modal-content">
    <h3>Get Our Curriculum For Free</h3>
      <div class="your-clock"></div>
      Until the next newsletter
    <img src="/img/curriculum-preview-modal.png"/>
    <p class="newsletter-info">
    Quality programming and web development tutorials, tips and tricks, and interview preparation delivered straight to your inbox every Monday morning.
    </p>
    <br>
  </div>

  <form class="form-inline" method="post">
    <div class="form-group">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email" id="email" placeholder="student@example.com">
    </div>
    <button type="submit" class="btn btn-md btn-color" formaction="/newsletter-signup">
      Get started learning!
    </button>
  </form>

</div>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/new.html.erb
<h1>New Response</h1>

<%= render 'form' %>

<%= link_to 'Back', responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @response.full_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @response.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @response.body %>
</p>

<%= link_to 'Edit', edit_response_path(@response) %> |
<%= link_to 'Back', responses_path %>

app/views/topics/index.html.erb
<div class="container">
  <h1>Listing All Topics</h1>

  <%= link_to "new topic", new_topic_path %>

  <br />
  <br />

  <ul>
    <% @topics.each do |topic| %>
      <li><%= link_to topic.name, topic %> | <%= link_to "edit", edit_topic_path(topic) %></li>
    <% end %>
  </ul>

</div>

app/views/topics/show.html.erb
<div class="container">
  <%= link_to "edit", edit_topic_path(@topic)  %> |
  <%= link_to "delete", topic_path, method: :delete, data: { confirm: "Are you sure?" } %>

  <h1><%= @topic.name %></h1>

  <div>
    <%= simple_format @topic.content %>
  </div>
</div>